id: IB10818E1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:45:57+00:00'
last_modified: '2022-06-08T06:04:11.617528+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD107152
  title: དབུ་མ་རྒྱན་རྩ་འགྲེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B200:
      image_group_id: I1PD107154
      title: ''
      total_pages: 466
      order: 1
      base_file: B200.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
